var res = {
    //font_TTF:{
    //    type:"font",
    //    name:"dht",
    //    srcs:["res/dht.TTF"]
    //},
    MainScene_json : "res/MainScene.json",
    StartScene_json : "res/StartScene.json",
    gameInfoLayer_json : "res/gameInfoLayer.json",
    caiquan_01:"res/caiquan_01.png",
    caiquan_02:"res/caiquan_02.png",
    caiquan_03:"res/caiquan_03.png",
    caiquan_04:"res/caiquan_04.png",
    caiquan_05:"res/caiquan_05.png",
    caiquan_06:"res/caiquan_06.png",
    caiquan_07:"res/caiquan_07.png",
    caiquan_08:"res/caiquan_08.png",
    caiquan_09:"res/caiquan_09.png",
    caiquan_10:"res/caiquan_10.png",
    caiquan_11:"res/caiquan_11.png",
    caiquan_12:"res/caiquan_12.png",
    caiquan_13:"res/caiquan_13.png",
    caiquan_14:"res/caiquan_14.png",
    caiquan_15:"res/caiquan_15.png",
    caiquan_16:"res/caiquan_16.png",
    caiquan_17:"res/caiquan_17.png",
    caiquan_18:"res/caiquan_18.png",
    caiquan_19:"res/caiquan_19.png",
    caiquan_20:"res/caiquan_20.png",
    caiquan_21:"res/caiquan_21.png",
    caiquan_22:"res/caiquan_22.png",
    caiquan_23:"res/caiquan_23.png",
    caiquan_25:"res/caiquan_25.png",
    caiquan_26:"res/caiquan_26.png",
    caiquan_27:"res/caiquan_27.png",
    caiquan_28:"res/caiquan_28.png",
    caiquan_29:"res/caiquan_29.png",
    caiquan_30:"res/caiquan_30.png",
    caiquan_31:"res/caiquan_31.png",
    caiquan_32:"res/caiquan_32.png",
    caiquan_33:"res/caiquan_33.png",
    caiquan_34:"res/caiquan_34.png",
    caiquan_35:"res/caiquan_35.png",
    caiquan_36:"res/caiquan_36.png",
    caiquan_37:"res/caiquan_37.png",
    caiquan_38:"res/caiquan_38.png",
    caiquan_39:"res/caiquan_39.png",
    caiquan_40:"res/caiquan_40.png",
    caiquan_41:"res/caiquan_41.png",
    caiquan_42:"res/caiquan_42.png",
    caiquan_43:"res/caiquan_43.png",
    caiquan_44:"res/caiquan_44.png",
    caiquan_45:"res/caiquan_45.png",
    caiquan_46:"res/caiquan_46.png",
    caiquan_47:"res/caiquan_47.png",
    caiquan_48:"res/caiquan_48.png",
    caiquan_49:"res/caiquan_49.png",
    caiquan_50:"res/caiquan_50.png",

    caiquan_51:"res/caiquan_51.png",
    caiquan_52:"res/caiquan_52.png",
    caiquan_53:"res/caiquan_53.png",
    caiquan_54:"res/caiquan_54.png",

    caiquan_n_g:"res/caiquan_n_g.png",
    caiquan_n1_1:"res/caiquan_n1_1.png",
    caiquan_n1_2:"res/caiquan_n1_2.png",
    caiquan_n2_1:"res/caiquan_n2_1.png",
    caiquan_n2_2:"res/caiquan_n2_2.png",
    caiquan_n3:"res/caiquan_n3.png",
    caiquan_n4:"res/caiquan_n4.png",
    caiquan_n5_1:"res/caiquan_n5_1.png",
    caiquan_n5_2:"res/caiquan_n5_2.png",
    caiquan_n5_3:"res/caiquan_n5_3.png",
    caiquan_n5_4:"res/caiquan_n5_4.png",
    caiquan_nwz_dhjl:"res/caiquan_nwz_dhjl.png",
    caiquan_nwz_jrxyg:"res/caiquan_nwz_jrxyg.png",
    caiquan_nwz_qd:"res/caiquan_nwz_qd.png",
    caiquan_nwz_tcyx:"res/caiquan_nwz_tcyx.png",
    caiquan_sz_1:"res/caiquan_sz_1.png",
    caiquan_sz_2:"res/caiquan_sz_2.png",
    caiquan_sz_3:"res/caiquan_sz_3.png",
    caiquan_sz_4:"res/caiquan_sz_4.png",
    caiquan_sz_5:"res/caiquan_sz_5.png",
    caiquan_sz_6:"res/caiquan_sz_6.png",
    caiquan_sz_7:"res/caiquan_sz_7.png",
    caiquan_sz_8:"res/caiquan_sz_8.png",
    caiquan_sz_9:"res/caiquan_sz_9.png",
    caiquan_sz_10:"res/caiquan_sz_10.png",
    caiquan_n6:"res/caiquan_n6.png",
    caiquan_n7:"res/caiquan_n7.png",
    caiquan_n8:"res/caiquan_n8.png"
};

var musics={
    bgmusic:"res/audio/bgmusic.mp3",
    s_1:"res/audio/1.mp3",
    s_2:"res/audio/2.mp3",
    s_3:"res/audio/3.mp3",
    s_4:"res/audio/4.mp3",
    s_5:"res/audio/5.mp3",
    s_6:"res/audio/6.mp3",
    s_7:"res/audio/7.mp3",
    s_8:"res/audio/8.mp3",
    s_9:"res/audio/9.mp3",
    s_10:"res/audio/10.mp3",
    s_11:"res/audio/11.mp3",
    s_12:"res/audio/12.mp3",
    s_13:"res/audio/13.mp3"
};
//if(cc.sys.os!== cc.sys.OS_ANDROID) {
//    musics={
//        bgmusic:"res/audio/bgmusic.mp3",
//        s_1:"res/audio/1.mp3",
//        s_2:"res/audio/2.mp3",
//        s_3:"res/audio/3.mp3",
//        s_4:"res/audio/4.mp3",
//        s_5:"res/audio/5.mp3",
//        s_6:"res/audio/6.mp3",
//        s_7:"res/audio/7.mp3",
//        s_8:"res/audio/8.mp3",
//        s_9:"res/audio/9.mp3",
//        s_10:"res/audio/10.mp3",
//        s_11:"res/audio/11.mp3",
//        s_12:"res/audio/12.mp3",
//        s_13:"res/audio/13.mp3"
//    };
//}

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}

var musiclist=[];
for (var i in musics) {
    musiclist.push(musics[i]);
}